/**:
  ros__parameters:
    min_longitudinal_offset: 2.03
    max_longitudinal_offset: 2.24
    min_lateral_offset: -0.84
    max_lateral_offset: 1.04
    min_height_offset: 0.95
    max_height_offset: 1.07
